### ISSUE TITLE
Parallelism using OpenMp

### ISSUE THREAD

**Issue by jgburet** [1475963/vrep-ga-cpp#11]

**Comment by jgburet** [comment]
https://github.com/1475963/vrep-ga-cpp/blob/testing/srcs/Simulation.cpp#L81
No.

We have to start and stop the simulation after each batch (of size 'number_of_threads') of individuals to process. Thing is, with the actual state of OpenMP, it is not possible to use 'barriers', 'master', etc inside a parallel execution. Thus, it makes the development tougher and less clean, as the parallel execution won't be over the individuals but over the batches of individuals.

**Comment by JeremyPouyet** [comment]
I don't agree with you that "it makes the development tougher and less clean, as the parallel execution won't be over the individuals but over the batches of individuals". If we parallelise only this loop, OpenMP will create a barrier (it's implicit as you don't create it but OpenMP does it for you) at the end of the loop so the execution won't continue after the loop before it ends. In this way, the simulation will be started and stopped when you want and you just have to add one `#pragma omp parallel for` around the loop, with maybe `i` as a shared variable.

**Comment by jgburet** [comment]
Please cf: https://github.com/1475963/vrep-ga-cpp/blob/enhancement/%2311/openMP/srcs/Simulation.cpp#L79
https://github.com/1475963/vrep-ga-cpp/blob/enhancement/%2311/openMP/srcs/Simulation.cpp#L84

Does it make more sense now?
